codeshine/urls.py
from django.urls import path

from . import views
from home.views import Handler404

app_name = "codeshine"

urlpatterns = [
    path('<str:page_code>/post/', views.post_assignment, name="post"),
    path('<str:page_code>/assignment-<str:assignment_code>/', views.specific_assignment, name="assignments"),
    path('<str:page_code>/assignment-<str:assignment_code>/submit/', views.post_submission, name="submit"),
    path('<str:page_code>/assignment-<str:assignment_code>/submissions/', views.submissions, name="submissions"),
    path('<str:page_code>/assignment-<str:assignment_code>/submission-<str:submission_code>/', views.specific_submission, name="submission"),
    path('<str:page_code>/assignment-<str:assignment_code>/submission-<str:submission_code>/evaluate', views.post_evaluation, name="evaluate"),
    path('<str:page_code>/assignment-<str:assignment_code>/submission-<str:submission_code>/comment', views.post_comment, name="comment"),
]

departments/urls.py
from django.urls import path, include

from . import views

app_name = "departments"

urlpatterns = [
    path('', views.all_departments, name="all_departments"),
    path('add/', views.add_department, name="add_department"),
    path('<str:code>-department/', views.specific_department, name="specific_department"),
    path('<str:code>-department/add-page/', views.add_page, name="add_page"),
]

diems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('departments/', include("departments.urls")),
    path('codeshine/', include("codeshine.urls")),
]
handler404 = "home.views.Handler404"

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
]

codeshine/models.py
from email.policy import default
from django.db import models

from accounts.models import User
from departments.models import Page


class Assignment(models.Model):
    By = models.ForeignKey(to=User, on_delete=models.CASCADE,
                           related_name="Assigned_By", blank=True, null=True)
    In = models.ForeignKey(to=Page, on_delete=models.CASCADE,
                           related_name="Assigned_In", blank=True, null=True)
    On = models.DateTimeField(auto_now=True)

    Title = models.CharField(max_length=128, blank=False, default="Untitled")
    Description = models.CharField(max_length=1024, blank=True)
    Instructions = models.TextField(blank=True)
    GettingStarted_Template = models.TextField(blank=True)
    max_points = models.IntegerField(blank=False, default=100)
    passing_points = models.IntegerField(blank=False, default=35)

    is_verified = models.BooleanField(blank=False, default=False)
    is_archive = models.BooleanField(blank=False, default=False)
    open_for_submission = models.BooleanField(blank=False, default=False)
    open_for_comment = models.BooleanField(blank=False, default=False)

    display_all_result = models.BooleanField(blank=False, default=False)
    display_verified_result = models.BooleanField(blank=False, default=False)
    display_ideal_result = models.BooleanField(blank=False, default=False)
    
    def __str__(self) -> str:
        return f"{self.Title} ({self.On.date()})"


class Submission(models.Model):
    By = models.ForeignKey(to=User, on_delete=models.CASCADE,
                           related_name="Submitter", blank=True, null=True)
    In = models.ForeignKey(to=Assignment, on_delete=models.CASCADE,
                           related_name="Submitted", blank=True, null=True)
    On = models.DateTimeField(auto_now=True)

    Assignment = models.TextField(blank=True)
    Points = models.IntegerField(blank=False, default=0)
    Remark = models.CharField(max_length=1024, blank=True)

    is_verified = models.BooleanField(blank=False, default=False)
    is_ideal = models.BooleanField(blank=False, default=False)
    
    def __str__(self) -> str:
        return f"{self.By} ({self.On.date()})"


class Comment(models.Model):
    By = models.ForeignKey(to=User, on_delete=models.CASCADE,
                           related_name="Commenter", blank=True, null=True)
    In = models.ForeignKey(to=Submission, on_delete=models.CASCADE,
                           related_name="Commented", blank=True, null=True)
    On = models.DateTimeField(auto_now=True)

    Theme = models.CharField(max_length=128, blank=True)
    Comment = models.TextField(blank=True)

    is_verified = models.BooleanField(blank=False, default=False)
    is_ideal = models.BooleanField(blank=False, default=False)

    def __str__(self) -> str:
        return f"{self.By} ({self.On.date()})"

codeshine/views.py
from django.shortcuts import render, get_object_or_404
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

from .models import *
from home.views import render_form_generic
from codeshine.models import Assignment, Submission, Comment
from departments.models import Page


def specific_assignment(request, page_code, assignment_code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    page = get_object_or_404(Page, Code=page_code)

    # Ensure user is in same department
    if not request.user.Department == page.Department:
        return render(request, "home/403.html", status=403)

    assignment = get_object_or_404(Assignment, pk=assignment_code)    
    my_submissions = Submission.objects.filter(In=assignment, By=request.user)
    all_submissions = Submission.objects.filter(In=assignment)

    class PostSubmissionForm(forms.Form):
        fieldAssignment = forms.CharField(
            label="Solution",
            widget=forms.Textarea,
            required=False,
            initial=assignment.GettingStarted_Template)

    max_marks = 0
    comments = []
    for submission in my_submissions:
        comments += [x for x in Comment.objects.filter(In=submission)]
        max_marks = max(submission.Points, max_marks)

    return render(request, "codeshine/index.html", {
        "title": f"Assignment - {assignment.Title}",
        "assignment": assignment,
        "submissions": my_submissions,
        "comments": comments,
        "all_submissions": all_submissions,
        "page_code": page_code,
        "assignment_code": assignment_code,
        "form": PostSubmissionForm(),
        "max_marks": max_marks,
    })


def post_assignment(request, page_code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    page = get_object_or_404(Page, Code=page_code)

    # Ensure user is in same department
    if not request.user.Department == page.Department:
        return render(request, "home/403.html", status=403)

    # Ensure user is teacher
    if not request.user.is_teacher:
        return render(request, "home/403.html", status=403)

    return_url = reverse("departments:specific_department", kwargs={
        "code": page.Department.Code
    })

    class PostAssignmentForm(forms.Form):
        fieldTitle = forms.CharField(
            label="Title", max_length=128, required=True, strip=True)
        fieldDescription = forms.CharField(
            label="Description", max_length=1024, required=False, strip=True)
        fieldMaxPoints = forms.IntegerField(
            label="Maximum Possible Points", min_value=0, initial=100, required=True)
        fieldPassingPoints = forms.IntegerField(
            label="Satisfactory Passing Points", min_value=0, initial=35, required=True)
        submission_choices = (("Yes", "Yes! Allow students to make submissions"),
                              ("No", "No! Close the submission feature for students"))
        fieldOpenForSubmission = forms.ChoiceField(
            label="Allow Submissions", required=True, choices=submission_choices)
        comment_choices = (("Yes", "Yes! let student comment on results/submissions"),
                           ("No", "No! results/submission are fixed, no grievance."))
        fieldOpenForComment = forms.ChoiceField(
            label="Allow Comments", required=True, choices=comment_choices)
        fieldInstructions = forms.CharField(
            label="Instructions", widget=forms.Textarea, required=False)
        fieldGettingStarted = forms.CharField(
            label="Getting Started Template", widget=forms.Textarea, required=False)

    form_title = "Create Assignment"
    form_to = reverse("codeshine:post", kwargs={"page_code": page_code})
    form_action = "Post Assignment"

    if not request.method == "POST":
        return render_form_generic(
            request, form_title, form_to, form_action, PostAssignmentForm())

    raw_form = PostAssignmentForm(request.POST)
    if not raw_form.is_valid():
        return render_form_generic(
            request, form_title, form_to, form_action, PostAssignmentForm(request.POST))

    try:
        form_data = raw_form.cleaned_data

        new_assignment = Assignment(
            By=request.user,
            In=page,
            Title=form_data["fieldTitle"],
            Description=form_data["fieldDescription"],
            Instructions=form_data["fieldInstructions"],
            GettingStarted_Template=form_data["fieldGettingStarted"],
            max_points=form_data["fieldMaxPoints"],
            passing_points=form_data["fieldPassingPoints"]
        )

        if form_data["fieldOpenForSubmission"] == "Yes":
            new_assignment.open_for_submission = True
        else:
            new_assignment.open_for_submission = False

        if form_data["fieldOpenForComment"] == "Yes":
            new_assignment.open_for_comment = True
        else:
            new_assignment.open_for_comment = False

        new_assignment.save()

    except Exception as massage:
        return render_form_generic(
            request, form_title, form_to, form_action,
            PostAssignmentForm(request.POST),
            "Something went wrong, please contact support team regarding exception '{}'".format(massage))

    return HttpResponseRedirect(return_url)


def submissions(request, page_code, assignment_code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    page = get_object_or_404(Page, Code=page_code)

    # Ensure user is in same department
    if not request.user.Department == page.Department:
        return render(request, "home/403.html", status=403)

    assignment = get_object_or_404(Assignment, pk=assignment_code)
    submissions = Submission.objects.filter(In=assignment)

    # Ensure user is teacher or is allowed by students
    if not request.user.is_teacher:
        return render(request, "home/403.html", status=403)

    submission_users = []
    all_submissions = []
    for submission in submissions:
        if submission.By not in submission_users:
            submission_users += [submission.By]
            all_submissions += [(submission.By,
                                 [x for x in submissions.filter(By=submission.By)])]

    return render(request, "codeshine/submissions.html", {
        "title": f"{assignment.Title}",
        "page_code": page_code,
        "assignment_code": assignment_code,
        "assignment": assignment,
        "submission_users": submission_users,
        "all_submissions": all_submissions,
    })


def specific_submission(request, page_code, assignment_code, submission_code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    page = get_object_or_404(Page, Code=page_code)

    # Ensure user is in same department
    if not request.user.Department == page.Department:
        return render(request, "home/403.html", status=403)

    assignment = get_object_or_404(Assignment, pk=assignment_code)
    submission = get_object_or_404(Submission, pk=submission_code)

    # Ensure user is teacher or the submission is of student them-self
    if not (request.user.is_teacher or request.user == submission.By):
        return render(request, "home/403.html", status=403)

    comments = [x for x in Comment.objects.filter(In=submission)]

    class PostEvaluationForm(forms.Form):
        fieldSubmissionPoints = forms.IntegerField(
            label="Evaluation Points",
            min_value=1,
            max_value=assignment.max_points,
            initial=submission.Points,
            required=True)
        fieldRemark = forms.CharField(
            label="Remark", max_length=1024, required=False,
            initial=submission.Remark)
        ideal_choices = (("No", "Maybe! but not suitable for sharing with others at result declaration"),
                         ("Yes", "Yes! and should be shared to all at result declaration"))
        fieldIdeal = forms.ChoiceField(
            label="Is ideal", initial="No", required=True, choices=ideal_choices)

    class PostCommentForm(forms.Form):
        fieldCommentTheme = forms.CharField(
            label="Theme", max_length=128, required=False)
        fieldComment = forms.CharField(
            label="Comment", widget=forms.Textarea, required=True)

    return render(request, "codeshine/submission.html", {
        "title": f"Submission #{submission.pk}",
        "page_code": page_code,
        "assignment_code": assignment_code,
        "submission_code": submission_code,
        "assignment": assignment,
        "submission": submission,
        "comments": comments,
        "form_evaluate": PostEvaluationForm(),
        "form_comment": PostCommentForm()
    })


def post_submission(request, page_code, assignment_code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    page = get_object_or_404(Page, Code=page_code)

    # Ensure user is in same department
    if not request.user.Department == page.Department:
        return render(request, "home/403.html", status=403)

    assignment = get_object_or_404(Assignment, pk=assignment_code)

    # Ensure user is teacher or is allowed by students
    if not (request.user.is_teacher or assignment.open_for_submission):
        return render(request, "home/405.html", status=405)

    return_url = reverse("codeshine:assignments", kwargs={
        "page_code": page_code,
        "assignment_code": assignment_code
    })

    class PostSubmissionForm(forms.Form):
        fieldAssignment = forms.CharField(

codeshine/templates/codeshine/submission.html
{% extends 'home/layout.html' %}

{% block title %}
CodeShine - Submission Details
{% endblock %}

{% block body %}
<div class="container">
    <p>
        <a href="{% url 'departments:specific_department' assignment.In.Department.Code %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
            </svg>
            Back to department </a>
    </p>

    {% if title %}
    <h1>
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-journal-check"
            viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
            <path
                d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
            <path
                d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
        </svg>
        {{ title }}
    </h1>
    {% endif %}
    {% if submission %}
    <p>
        This is the solution submitted on <u>{{ submission.On }}</u> by <u>{{ submission.By.username|capfirst }}</u> for
        the assignment titled <u>{{ assignment.Title|capfirst }}</u>.
    </p>

    <div class="container render-markdown">
        <textarea class="render-markdown">{{ submission.Assignment }}</textarea>
    </div>
    {% endif %}

    {% if form_evaluate and request.user.is_teacher %}
    <div class="container warning-container">
        <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="currentColor" class="bi bi-patch-check"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M10.354 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
                <path
                    d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911l-1.318.016z" />
            </svg>
            Evaluate
        </h3>

        <form action="{% url 'codeshine:evaluate' page_code assignment_code submission_code %}" method="post">
            {% csrf_token %}
            {% for field in form_evaluate %}
            {{ field.label_tag }}
            {{ field }}
            {% endfor %}
            <input type="submit" value="Post Evaluation">
        </form>
    </div>
    {% endif %}
</div>

{% if submission %}





{% if comments or request.user.is_teacher %}
<div class="container">
    <h2>
        <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="currentColor" class="bi bi-chat-left-text"
            viewBox="0 0 16 16">
            <path
                d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
            <path
                d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
        </svg>
        Comments
    </h2>

    {% for comment in comments%}
    {% if comment.By.is_teacher != True %}
    <p>{{ comment.On }} | By Dear {{ comment.By.username|capfirst }},</p>
    <div class="container comment-container">
        {% if comment.Theme %}<h1 class="theme">{{ comment.Theme }}</h1>{% endif %}
        {% if comment.Comment %}<textarea class="render-markdown">{{ comment.Comment }}</textarea>{% endif %}
    </div>
    {% else %}
    <p>
        {{ comment.On }}
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person"
            viewBox="0 0 16 16">
            <path
                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
        </svg>
        By Respected {{ comment.By.username|capfirst }} Sir/Madam,
    </p>
    <div class="container comment-container teacher">
        {% if comment.Theme %}<h1 class="theme">{{ comment.Theme }}</h1>{% endif %}
        {% if comment.Comment %}<textarea class="render-markdown">{{ comment.Comment }}</textarea>{% endif %}
    </div>
    {% endif %}
    {% endfor %}
    {% if request.user.is_teacher or assignment.open_for_comment %}
    {% if form_comment %}
    <div class="container warning-container">
        <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="currentColor" class="bi bi-plus-lg"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
            </svg>
            Post
        </h3>
        <form action="{% url 'codeshine:comment' page_code assignment_code submission_code %}" method="post">
            {% csrf_token %}
            {% for field in form_comment %}
            {{ field.label_tag }}
            {{ field }}
            {% endfor %}
            <input type="submit" value="Post Comment">
        </form>
    </div>
    {% endif %}
    {% endif %}
</div>
{% endif %}




{% else %}
<div class="container warning-container">
    <h1>Warning</h1>
    <p>No Submission Details Available</p>
</div>
<br>
{% endif %}
{% endblock %}