accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.account_index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register")
]

diems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('departments/', include("departments.urls")),
    path('codeshine/', include("codeshine.urls")),
]
handler404 = "home.views.Handler404"

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from departments.models import Department

class User(AbstractUser):
    Department = models.ForeignKey(
        to=Department, on_delete=models.CASCADE, related_name="Mentor", blank=True, null=True)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_head = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms


from .models import Department, User
from home.views import render_form_generic


def account_index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("home:index"))
    else:
        return HttpResponseRedirect(reverse("accounts:login"))


def login_view(request):
    class LoginForm(forms.Form):
        username = forms.CharField(
            label="Username", max_length=100, min_length=1, strip=True, required=True)
        password = forms.CharField(
            label="Password", widget=forms.PasswordInput(), required=True)

    form_title = "Login"
    form_to = reverse("accounts:login")
    form_action = "Authenticate me"

    # If user don't POST data, provide the form
    if not request.method == "POST":
        return render_form_generic(
            request, form_title, form_to, form_action, LoginForm())

    # Ensure fields are valid
    form = LoginForm(request.POST)
    if not form.is_valid():
        return render_form_generic(request, form_title, form_to, form_action,
                                   LoginForm(request.POST),
                                   error="Form is not valid, make necessary changes")

    data = form.cleaned_data

    # Check if authentication successful
    username = data["username"]
    password = data["password"]
    user = authenticate(request, username=username, password=password)
    if user is None:
        return render_form_generic(request, form_title, form_to, form_action,
                                   LoginForm(request.POST),
                                   error="Invalid username and/or password")

    # Log the user in
    login(request, user)
    return HttpResponseRedirect(reverse("home:index"))


def logout_view(request):
    # Log the user out
    logout(request)
    return HttpResponseRedirect(reverse("home:index"))


def register_view(request):
    class RegistrationForm(forms.Form):
        PositionChoices = [("student", "As a Student"),
                           ("teacher", "As a Teacher")]

        username = forms.CharField(
            label="Username", max_length=100, min_length=1, strip=True, required=True)
        password = forms.CharField(
            label="Password", widget=forms.PasswordInput(), required=True)
        confirmation = forms.CharField(
            label="Retype Password", widget=forms.PasswordInput(), required=True)
        email = forms.EmailField(
            label="Email", max_length=100, min_length=1, required=True)
        position = forms.ChoiceField(
            label="Position", choices=PositionChoices, required=True)
        department = forms.ModelChoiceField(
            queryset=Department.objects.all(), empty_label="None", required=True)

    form_title = "Register"
    form_to = reverse("accounts:register")
    form_action = "Register me"

    # If user don't POST data, provide the form
    if not request.method == "POST":
        return render_form_generic(
            request, form_title, form_to, form_action, RegistrationForm())

    # Ensure fields are valid
    form = RegistrationForm(request.POST)
    if not form.is_valid():
        return render_form_generic(request, form_title, form_to, form_action,
                                   RegistrationForm(request.POST),
                                   error="Form is not valid, make necessary changes")

    data = form.cleaned_data
    # Ensure password matches confirmation
    if data["password"] != data["confirmation"]:
        return render_form_generic(request, form_title, form_to, form_action,
                                   RegistrationForm(request.POST),
                                   error="Passwords must match")

    # Attempt to create new user
    try:
        # Collect Requirements
        username = data["username"]
        email = data["email"].lower()
        password = data["password"]

        # Make space for the user
        user = User.objects.create_user(username, email, password)
        user.Department = data["department"]
        user.is_student = True if data["position"] == "student" else False
        user.is_teacher = True if data["position"] == "teacher" else False
        user.save()

    except Exception as massage:
        return render_form_generic(request, form_title, form_to, form_action,
                                   RegistrationForm(request.POST),
                                   error="Something went wrong, please contact support team regarding exception '{}'".format(massage))

    # Log the user in
    login(request, user)
    return HttpResponseRedirect(reverse("home:index"))

accounts/templates/accounts/index.html
{% extends 'home/layout.html' %}

{% block title %}Details{% endblock %}
{% block body %}

{% if message %}
<h1>Massages</h1>
<li>{{ message }}</li>
{% endif %}

<h1>Useful Links</h1>
{% if logged_in %}
{{ username }}(<a href="{% url 'accounts:index' %}">info</a>) - <a href="{% url 'accounts:logout' %}">Logout</a>
{% else %}
<a href="{% url 'accounts:register' %}">Register</a> - <a href="{% url 'accounts:login' %}">Login</a>
{% endif %}

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'home/layout.html' %}

{% block title %}Login{% endblock %}
{% block body %}
{% if message %}
<h1>Messages</h1>
<li>{{ message }}</li>
{% endif %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <div>
        <input type="submit" value="Authenticate me">
    </div>
</form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'home/layout.html' %}

{% block title %}Register{% endblock %}
{% block body %}
{% if message %}
<h1>Messages</h1>
<li>{{ message }}</li>
{% endif %}
<h1>Register</h1>
<form action="{% url 'accounts:register' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <div>
        <input type="submit" value="Register" id="register">
    </div>
</form>
{% endblock %}