codeshine/urls.py
from django.urls import path

from . import views
from home.views import Handler404

app_name = "codeshine"

urlpatterns = [
    path('<str:page_code>/post/', views.post_assignment, name="post"),
    path('<str:page_code>/assignment-<str:assignment_code>/', views.specific_assignment, name="assignments"),
    path('<str:page_code>/assignment-<str:assignment_code>/submit/', views.post_submission, name="submit"),
    path('<str:page_code>/assignment-<str:assignment_code>/submissions/', views.submissions, name="submissions"),
    path('<str:page_code>/assignment-<str:assignment_code>/submission-<str:submission_code>/', views.specific_submission, name="submission"),
    path('<str:page_code>/assignment-<str:assignment_code>/submission-<str:submission_code>/evaluate', views.post_evaluation, name="evaluate"),
    path('<str:page_code>/assignment-<str:assignment_code>/submission-<str:submission_code>/comment', views.post_comment, name="comment"),
]

departments/urls.py
from django.urls import path, include

from . import views

app_name = "departments"

urlpatterns = [
    path('', views.all_departments, name="all_departments"),
    path('add/', views.add_department, name="add_department"),
    path('<str:code>-department/', views.specific_department, name="specific_department"),
    path('<str:code>-department/add-page/', views.add_page, name="add_page"),
]

diems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('departments/', include("departments.urls")),
    path('codeshine/', include("codeshine.urls")),
]
handler404 = "home.views.Handler404"

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
]

departments/models.py
from django.db import models


class Department(models.Model):
    Name = models.CharField(max_length=64)
    Code = models.CharField(max_length=16, unique=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.Name}"


class Page(models.Model):
    Name = models.CharField(max_length=64)
    Code = models.CharField(max_length=32, unique=True)
    Department = models.ForeignKey(
        to=Department, on_delete=models.CASCADE, related_name="Offered_Course")
    is_verified = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.Name}"

departments/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

from .models import *
from home.views import render_form_generic
from accounts.models import *
from codeshine.models import Assignment


def specific_department(request, code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    department = get_object_or_404(Department, Code=code)

    # Ensure user is in same department
    if not request.user.Department == department:
        return render(request, "home/403.html", status=403)

    class AddPageForm(forms.Form):
        Name = forms.CharField(
            label="Name", max_length=64, min_length=1, strip=True, required=True)
        Code = forms.CharField(
            label="Code (unique)", max_length=32, min_length=1, strip=True, required=True)

    assignments = []
    pages = get_list_or_404(Page, Department=department)
    for page in pages:
        assignments += [x for x in Assignment.objects.filter(
            In=page).order_by("-pk")]

    return render(request, "departments/index.html", {
        "title": f"{department.Name} Department",
        "pages": [x for x in pages],
        "assignments": assignments,
        "code": code,
        "form": AddPageForm()
    })


def all_departments(request):
    # Ensure the user is super user
    if not request.user.is_superuser:
        return render(request, "home/403.html", status=403)

    class AddDepartmentForm(forms.Form):
        Name = forms.CharField(
            label="Name", max_length=64, min_length=1, strip=True, required=True)
        Code = forms.CharField(
            label="Code (unique)", max_length=16, min_length=1, strip=True, required=True)

    return render(request, "departments/list.html", {
        "title": "Department Activity Management",
        "departments": [x for x in Department.objects.all()],
        "form": AddDepartmentForm(),
    })


def add_department(request):
    # Ensure the user is superuser
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse("home:index"))

    class AddDepartmentForm(forms.Form):
        Name = forms.CharField(
            label="Name", max_length=64, min_length=1, strip=True, required=True)
        Code = forms.CharField(
            label="Code (unique)", max_length=16, min_length=1, strip=True, required=True)

    return_url = reverse("departments:all_departments")

    if not request.method == "POST":
        return HttpResponseRedirect(return_url)

    raw_form = AddDepartmentForm(request.POST)
    if not raw_form.is_valid():
        return render(request, "home/400.html", context={
            "return_url": return_url,
            "backup_data": AddDepartmentForm(request.POST)
        })

    try:
        form_data = raw_form.cleaned_data

        department_name = form_data["Name"].title()
        department_code = form_data["Code"].lower()
        new_department = Department(Name=department_name, Code=department_code)
        new_department.save()

        new_page = Page(Name="Admin",
                        Code=f"{department_code}-admin",
                        Department=new_department)
        new_page.save()

    except Exception as exception:
        return render(request, "home/400.html", context={
            "exception": exception,
            "return_url": return_url,
            "backup_data": AddDepartmentForm(request.POST)
        })

    return HttpResponseRedirect(return_url)


def add_page(request, code):
    # Ensure user is authenticated
    if not request.user.is_authenticated:
        return render(request, "home/401.html", status=401)

    # Ensure user is in same department
    if not request.user.Department.Code == code:
        return render(request, "home/403.html", status=403)

    # Ensure user is teacher
    if not request.user.is_teacher:
        return render(request, "home/403.html", status=403)

    return_url = reverse("departments:specific_department", kwargs={
        "code": code
    })

    class AddPageForm(forms.Form):
        Name = forms.CharField(
            label="Name", max_length=64, min_length=1, strip=True, required=True)
        Code = forms.CharField(
            label="Code (unique)", max_length=32, min_length=1, strip=True, required=True)

    if not request.method == "POST":
        return HttpResponseRedirect(return_url)

    raw_form = AddPageForm(request.POST)
    if not raw_form.is_valid():
        return render(request, "home/400.html", context={
            "return_url": return_url,
            "backup_data": AddPageForm(request.POST)
        })

    try:
        form_data = raw_form.cleaned_data
        if request.user.is_teacher:
            new_page = Page(
                Name=form_data["Name"].title(),
                Code=f'{request.user.Department.Code}-{form_data["Code"].lower()}',
                Department=request.user.Department)
            new_page.save()

    except Exception as exception:
        return render(request, "home/400.html", context={
            "exception": exception,
            "return_url": return_url,
            "backup_data": AddPageForm(request.POST)
        })

    return HttpResponseRedirect(return_url)

departments/templates/departments/index.html
{% extends 'home/layout.html' %}

{% block title %}
Department
{% endblock %}
{% block body %}
<div class="container">
    <h1>
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-gem"
            viewBox="0 0 16 16">
            <path
                d="M3.1.7a.5.5 0 0 1 .4-.2h9a.5.5 0 0 1 .4.2l2.976 3.974c.149.185.156.45.01.644L8.4 15.3a.5.5 0 0 1-.8 0L.1 5.3a.5.5 0 0 1 0-.6l3-4zm11.386 3.785-1.806-2.41-.776 2.413 2.582-.003zm-3.633.004.961-2.989H4.186l.963 2.995 5.704-.006zM5.47 5.495 8 13.366l2.532-7.876-5.062.005zm-1.371-.999-.78-2.422-1.818 2.425 2.598-.003zM1.499 5.5l5.113 6.817-2.192-6.82L1.5 5.5zm7.889 6.817 5.123-6.83-2.928.002-2.195 6.828z" />
        </svg>
        {{ title }}
    </h1>
    <p>
        Welcome to the {{ title }}! Here, you'll find a variety of <b>assignments</b> posted by your instructors
        that are designed to help you develop your skills and knowledge in your chosen field of study. These assignments
        are organized by <b>pages</b>, which serve as the central location for posting and accessing assignments related
        to a particular topic or course. Whether you're a new student just starting out, or an experienced professional
        looking to expand your knowledge, our department is committed to providing you with a challenging and rewarding
        learning experience. So take a look around, explore our <b>pages</b>, and don't hesitate to ask your instructors
        if you have any questions or concerns. We're here to help you succeed!
    </p>

    {% if code and request.user.is_teacher%}
    <details>
        <summary>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                class="bi bi-arrows-expand" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M1 8a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 8ZM7.646.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 1.707V5.5a.5.5 0 0 1-1 0V1.707L6.354 2.854a.5.5 0 1 1-.708-.708l2-2ZM8 10a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 14.293V10.5A.5.5 0 0 1 8 10Z" />
            </svg>
            Add Page
        </summary>
        <div class="container warning-container">
            <h2>
                <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="currentColor" class="bi bi-plus-lg"
                    viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                        d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
                </svg>
                Add Page
            </h2>
            <form action="{% url 'departments:add_page' code %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
                {% endfor %}
                <input type="submit" value="Add Page">
            </form>
        </div>
    </details>

    {% endif %}
</div>



{% if pages %}
{% for page in pages %}
<div class="container">
    <h2>{{ page.Name }} Page <small>({{ page.Code|lower }})</small>
    </h2>
    {% if request.user.is_teacher %}
    <p>
        <a href="{% url 'codeshine:post' page.Code %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-plus-circle"
                viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                <path
                    d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
            </svg>
            Post assignment
        </a>
    </p>
    {% endif %}

    {% if assignments %}
    {% for assignment in assignments %}
    {% if assignment.In == page %}
    <br>
    <h3>
        <svg xmlns="http://www.w3.org/2000/svg" width="42" height="42" fill="currentColor"
            class="bi bi-journal-bookmark-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M6 1h6v7a.5.5 0 0 1-.757.429L9 7.083 6.757 8.43A.5.5 0 0 1 6 8V1z" />
            <path
                d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
            <path
                d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
        </svg>
        {{ assignment.Title|title }}
    </h3>
    <p>
        <a href="{% url 'codeshine:assignments' page.Code assignment.pk %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-eye"
                viewBox="0 0 16 16">
                <path
                    d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
            </svg>
            View Assignment
        </a>

        {% if request.user.is_teacher %}
        <a href="{% url 'codeshine:submissions' page.Code assignment.pk %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                class="bi bi-check2-circle" viewBox="0 0 16 16">
                <path
                    d="M2.5 8a5.5 5.5 0 0 1 8.25-4.764.5.5 0 0 0 .5-.866A6.5 6.5 0 1 0 14.5 8a.5.5 0 0 0-1 0 5.5 5.5 0 1 1-11 0z" />
                <path
                    d="M15.354 3.354a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l7-7z" />
            </svg>
            All Submissions
        </a>
        {% endif %}

        <br>
        {{ assignment.On }}
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person"
            viewBox="0 0 16 16">
            <path
                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
        </svg>
        By Respected {{ assignment.By.username|capfirst }} Sir/Madam,

        <br>
        <u>Description:</u>
        {{ assignment.Description }}
    </p>
    {% endif %}
    {% endfor %}
    {% endif %}
</div>
{% endfor %}
{% else %}
<div class="container warning-container">
    <h1>Warning</h1>
    <p>No Pages</p>
</div>
{% endif %}

{% endblock %}

departments/templates/departments/list.html
{% extends 'home/layout.html' %}

{% block title %}
All Departments
{% endblock %}
{% block body %}
{% if title %}
<div class="container">
  <h1>{{ title }}</h1>
</div>
{% endif %}

<div class="container">
  {% if departments %}
  {% for department in departments %}
  <h3>[<a href="{% url 'departments:specific_department' department.Code %}">{{ department.Code|upper }}</a>]: {{ department.Name }}
    Department</h3>
  {% endfor %}
  {% else %}
  <li>No Departments</li>
  {% endif %}
  <div class="container warning-container">
    <h1>Add Department</h1>
    <form action="{% url 'departments:add_department' %}" method="post">
      {% csrf_token %}
      {% for field in form %}
      {{ field.label_tag }}
      {{ field }}
      {% endfor %}
      <input type="submit" value="Create Department">
    </form>
  </div>
</div>


{% endblock %}